require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - db/**/*.rb
    - lib/**/*.rb
    - spec/**/*.rb
  Exclude:
    - bin/**/*
    - node_modules/**/*
    - vendor/**/*
    - config/environments/development.rb
    - config/environments/production.rb
    - db/**/*
  DisplayCopNames: true

Layout/LineLength:
  Max: 100
  AllowedPatterns: ['\A#']

Metrics/ClassLength:
  Max: 350

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Max: 200

Metrics/ParameterLists:
  Max: 7

Style/Documentation:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Style/SingleArgumentDig:
    Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
