version: "3"
services:
  rails:
    build: .
    command: bash -c "
      rm -f tmp/pids/server.pid &&
      bundle exec rails db:drop &&
      bundle exec rails db:create &&
      bundle exec rails db:migrate &&
      bundle exec rails db:seed &&
      bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: rails_backend
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
